apiVersion: v1
kind: Secret
metadata:
  name: __SECRET_NAME__
type: Opaque
stringData:
  rootUser: "__MYSQL_ROOT_USER__"
  rootHost: "__MYSQL_ROOT_HOST__"
  rootPassword: "__MYSQL_ROOT_PASSWORD__"
